### ISSUE TITLE
Crash: `GlobalData.java line 19`

### ISSUE THREAD

**Issue by zeoowl-dev** [teogor/ceres#27]
Crash: `GlobalData.java line 19`

```txt
Caused by java.lang.NullPointerException
       at dev.teogor.ceres.core.global.GlobalData.getActivity(GlobalData.java:19)
       at dev.teogor.ceres.ads.formats.AppOpenAd.show(AppOpenAd.java:19)
       at dev.teogor.ceres.ads.startup.AdsProvider.showAd(AdsProvider.java:69)
       at android.app.Application.dispatchActivityStarted(Application.java:405)
       at android.app.Activity.dispatchActivityStarted(Activity.java:1406)
       at android.app.Activity.onStart(Activity.java:1922)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:6)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
       at android.app.Activity.performStart(Activity.java:8315)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4136)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by teogor** [comment]
@zeoowl-dev, can you provide more details? for instance when does the crash occur

**Comment by zeoowl-dev** [comment]
Most of the time the `AppOpenAd` is shown

**Comment by teogor** [comment]
Understood. In that case probably the crash occurs due to the activity that was instantiated with the ad

**Comment by teogor** [comment]
Thank you for your feedback, @zeoowl-dev. Currently this library is in ALPHA therefore we are constantly trying to improve the performance.
