### ISSUE TITLE
AppOpenAd is empty

### ISSUE THREAD

**Issue by teogor** [teogor/ceres#50]
In some cases the app open as is empty therefore the activity's overlay is shown; this will look like the UI freezes and it requires an `onBackPressed` event.

Possible reason: it has to do with the cache flow for ad

**Comment by teogor** [comment]
To watch #51 - probably it will fix this problem, but still an asserter is required here

**Comment by teogor** [comment]
Problem not fixed. Will have to fully debug this.

I'll post here the progress.

**Comment by teogor** [comment]
upon checking this error occurs due to attempting to call showing ad on destroyed web-view

```txt
Application attempted to call on a destroyed WebView
  java.lang.Throwable
  at org.chromium.android_webview.AwContents.m(chromium-TrichromeWebViewGoogle.aab-stable-530409133:10)
  at com.android.webview.chromium.WebViewChromium.setBackgroundColor(chromium-TrichromeWebViewGoogle.aab-stable-530409133:32)
  at android.webkit.WebView.setBackgroundColor(WebView.java:3060)
  at com.google.android.gms.ads.internal.webview.y.ah(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314:0)
  at com.google.android.gms.ads.internal.overlay.k.v(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314:33)
  at com.google.android.gms.ads.internal.overlay.k.d(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314:23)
  at com.google.android.gms.ads.internal.overlay.client.a.bQ(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314:23)
  at aeu.onTransact(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314:4)
  at android.os.Binder.transact(Binder.java:1100)
  at com.google.android.gms.internal.ads.zzarz.zzbl(com.google.android.gms:play-services-ads-base@@21.3.0:2)
  at com.google.android.gms.internal.ads.zzbza.zzk(com.google.android.gms:play-services-ads-lite@@21.3.0:3)
  at com.google.android.gms.ads.AdActivity.onCreate(com.google.android.gms:play-services-ads-lite@@21.3.0:3)
  at android.app.Activity.performCreate(Activity.java:8290)
  at android.app.Activity.performCreate(Activity.java:8270)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4085)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4277)
  at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loopOnce(Looper.java:226)
  at android.os.Looper.loop(Looper.java:313)
  at android.app.ActivityThread.main(ActivityThread.java:8751)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
