### ISSUE TITLE
Crash when loading activity that extends BaseActivity

### ISSUE THREAD

**Issue by zeoowl-dev** [teogor/ceres#56]
Here is the error
```error
java.lang.NullPointerException: null cannot be cast to non-null type androidx.navigation.fragment.NavHostFragment
  at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6032)
  at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6077)
  at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
  at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loopOnce(Looper.java:226)
  at android.os.Looper.loop(Looper.java:313)
  at android.app.ActivityThread.main(ActivityThread.java:8751)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
  Caused by: java.lang.NullPointerException: null cannot be cast to non-null type androidx.navigation.fragment.NavHostFragment
  at dev.teogor.ceres.extensions.ActivityExtKt.findNavController(ActivityExt.kt:28)
  at dev.teogor.ceres.components.app.BaseActivity.findNavController(BaseActivity.kt:262)
  at dev.teogor.ceres.components.app.BaseActivity.onDestroy(BaseActivity.kt:181)
  at android.app.Activity.performDestroy(Activity.java:8571)
  at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
  at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6019)
  at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6077) 
  at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47) 
  at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443) 
  at android.os.Handler.dispatchMessage(Handler.java:106) 
  at android.os.Looper.loopOnce(Looper.java:226) 
  at android.os.Looper.loop(Looper.java:313) 
  at android.app.ActivityThread.main(ActivityThread.java:8751) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
```

**Comment by teogor** [comment]
It looks like this happens because the base fragment was not annotated as `null` in `ActivityExt.kt` from the `ceres:extensions` module.

This crash will be fixed with priority
