### ISSUE TITLE
`NullPointerException` for `BaseActivity.getBinding(BaseActivity.kt:62)`

### ISSUE THREAD

**Issue by zeoowl-dev** [teogor/ceres#75]
Here is the error:

```txt
java.lang.NullPointerException
  at dev.teogor.ceres.components.app.BaseActivity.getBinding(BaseActivity.kt:62)
  at dev.teogor.ceres.components.app.BaseActivity.setSplashScreenExitAnimation$lambda-10$lambda-6$lambda-5(BaseActivity.kt:226)
  at dev.teogor.ceres.components.app.BaseActivity.$r8$lambda$K6HtujfAO6UnHkTEMAPvvXIWmtg(BaseActivity.kt)
  at dev.teogor.ceres.components.app.BaseActivity$$ExternalSyntheticLambda5.onAnimationUpdate(D8$$SyntheticClass)
  at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1283)
  at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1207)
  at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1248)
  at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:546)
  at android.animation.ValueAnimator.start(ValueAnimator.java:959)
  at android.animation.ValueAnimator.start(ValueAnimator.java:969)
  at dev.teogor.ceres.components.app.BaseActivity.setSplashScreenExitAnimation$lambda-10(BaseActivity.kt:245)
  at dev.teogor.ceres.components.app.BaseActivity.$r8$lambda$KR9LJo7aGUe8b5StElwh-6Y5XQk(BaseActivity.kt)
  at dev.teogor.ceres.components.app.BaseActivity$$ExternalSyntheticLambda0.onSplashScreenExit(D8$$SyntheticClass)
  at androidx.core.splashscreen.SplashScreen$Impl.dispatchOnExitAnimation$lambda-3(SplashScreen.kt:377)
  at androidx.core.splashscreen.SplashScreen$Impl.$r8$lambda$-PV0PfxsoH5D7yqG9wGMqLSg-T0(SplashScreen.kt)
  at androidx.core.splashscreen.SplashScreen$Impl$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
  at android.view.Choreographer.doCallbacks(Choreographer.java:580)
  at android.view.Choreographer.doFrame(Choreographer.java:549)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5221)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

API - 21

**Comment by teogor** [comment]
calling `binding` on non-safe type
